name: Emtion Dectation CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Code checkout
      uses: actions/checkout@v3
      
    - name: Docker image build
      run: docker build -t emtion-dectation .
      
    - name: Success message
      run: echo "Emtion Dectation System successfully deployed!"
